# Generated by Django 3.1.2 on 2020-12-05 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='listing',
        ),
        migrations.AddField(
            model_name='listing',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applicant.contract'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
