# Generated by Django 3.1.2 on 2020-12-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_applicant_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(blank=True, default='/media/files/resume.txt', null=True, upload_to='files'),
        ),
    ]
