# Generated by Django 3.1.2 on 2020-12-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0006_auto_20201205_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=6000),
        ),
    ]
