# Generated by Django 3.1.2 on 2020-12-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0007_auto_20201205_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=12000),
        ),
    ]
