# Generated by Django 3.1.2 on 2020-12-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0008_auto_20201205_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='job_title',
            field=models.CharField(max_length=1000),
        ),
    ]
