# Generated by Django 3.1.2 on 2020-12-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0010_auto_20201205_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
